apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: helm-deployment
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: helm-deployment
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: helm-deployment
    spec:
      containers:
      - name: spinnaker
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 80
