kind: Service
apiVersion: v1
metadata:
  name: helm-deployment-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: helm-deployment
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort
